# Generated by debtap
# Maintainer: kolide
# Contributor: kolide
pkgname=launcher-kolide-k2
pkgver=0.11.23
pkgrel=1
pkgdesc="No description given."
arch=('x86_64')
url="http://www.kolide.com"
license=('')
groups=('')
backup=('etc/kolide-k2/launcher.flags' 'etc/kolide-k2/secret')
options=('!strip' '!emptydirs')
source_x86_64=("kolide.deb")
sha512sums_x86_64=('0cfa46938351102c9e5a2d13d3629ef1541329a0223b441d3df64392ddf8a42fc42c9726cc68d1098c1d11a8446f5836b0ee7dadec680819220ceba5f1e7d83f')

package(){
	tar xzf data.tar.gz -C "${pkgdir}"
	cd "${pkgdir}" || return
	mkdir -p usr/lib 2> /dev/null; mv lib/* usr/lib; rm -rf lib
	cd ..
}
